version: "3"

vars:
  APP_PATH: ./

tasks:
  default:
    cmds:
      - task -l
    silent: true

  upgrade:
    desc: Upgrade packages
    dir: "{{.APP_PATH}}"
    cmds:
      - uv lock --upgrade
    #silent: true

  freeze:
    desc: Freeze packages
    dir: "{{.APP_PATH}}"
    cmds:
      - uv lock

  sync-dev:
    desc: Sync Dev
    dir: "{{.APP_PATH}}"
    cmds:
      - uv sync --dev --frozen --link-mode=copy --no-editable --no-install-project

  sync-prod:
    desc: Sync Prod
    dir: "{{.APP_PATH}}"
    cmds:
      - uv sync --frozen --link-mode=copy --no-editable --no-install-project
